name: vulgatizer

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  vulgatizer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install python-dateutil
        pip install git+https://github.com/OpenPecha/CommonSpell.git
    - name: Create vulgate text
      run: |
        import os
        from openpecha.core.ids import get_open_pecha_id
        from openpecha.core.pecha import OpenPechaFS
        from pathlib import Path
        from CommonSpell.plain_text import PlainTextCommonSpeller

        def run_common_speller(witness_dir):
            pecha_id = get_open_pecha_id()
            common_spell_opf_path = Path(f'./common_spell/{pecha_id}.opf')
            try:
                witness_paths = list(witness_dir.iterdir())
            except:
                print("witness directory doesn't exist")
                return None
            witness_paths.sort()
            op_output = OpenPechaFS(common_spell_opf_path)
            common_speller = PlainTextCommonSpeller(op_output)
            for witness_path in witness_paths:
                common_speller.add_witness(witness_path)
            common_speller.create_vulgate()
            return vulga_opf_path

        witness_dir = Path('./witnesses')
        run_common_speller(witness_dir)
      shell: python

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Added or updated review dir
